version: '3.8'

services:
  lobe-chat:
    image: lobehub/lobe-chat
    container_name: lobe-chat
    restart: always
    ports:
      - '3210:3210'
    environment:
      OPENAI_API_KEY: sk-xxxx
      OPENAI_PROXY_URL: https://api-proxy.com/v1
      ACCESS_CODE: lobe66
    depends_on:
      - pg
      - minio

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - '11434:11434'
    healthcheck:
      test: ["CMD", "ollama", "ps"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - OLLAMA_KEEP_ALIVE=5m
      - OLLAMA_FLASH_ATTENTION=0
    volumes:
      - ./ollama_models:/root/.ollama

  pg:
    image: pgvector/pgvector:pg16
    container_name: pg
    restart: always
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=lobe'
      - 'POSTGRES_PASSWORD=password123'
    volumes:
      - './db:/var/lib/postgresql/data'

  minio:
    image: minio/minio
    container_name: lobe-minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - './s3_data:/etc/minio/data'
    environment:
      - 'MINIO_ROOT_USER=admin'
      - 'MINIO_ROOT_PASSWORD=password123'
      - 'MINIO_DOMAIN=lobe-s3-api.example.com'
      - 'MINIO_API_CORS_ALLOW_ORIGIN=https://lobe.example.com' # Your LobeChat's domain name.
    restart: always
    command: >
      server /etc/minio/data --address ":9000" --console-address ":9001"